### ISSUE TITLE
Support Travis-CI for HTML build

### ISSUE THREAD

**Issue by kazuki43zoo** [terasolunaorg/guideline#1345]
## Description
HTML build support on Travis-CI.

## Possible Solutions
Add `.travis.yml` as follow:

```yml
sudo: false
language: python
python:
  - "3.4"

install:
  - pip install --upgrade pip
  - pip install -q -r requirements.txt

script:
  - sh ./build-html.sh
  - sh ./build-html_en.sh
```

Pdf build will not support by this issue.
By default, Tex(Latex) environment is not installed on Travis-CI.

## Fix Version/s
- [x] 5.1.0
- [x] 5.0.2
- [x] 1.0.4

## Issue Links
N/A
